### ISSUE TITLE
not working on 3440 x 1440

### ISSUE THREAD

**Issue by steavewithana** [Crypto90/Wolcen-Socket-Roller#1]
https://streamable.com/lyw49

video of program rolling past the selected sockets and stopping on wrong sockets

**Comment by Crypto90** [comment]
The tool scans the text color and not the socket icon.
Thats how it is supposed to work!
For stopping on wrong sockets (rerolls once more if a match got found) use the last version 1.8.9 I just released. This got caused if we click too fast and the server/game is slower. I added a value field to change the sleep duration in milliseconds which it waits after reroll got clicked.
I increased this value also from 100ms to 200ms which works way better now.

**Comment by Crypto90** [comment]
Another known issue I got reported is the windows scaling.
Make sure your windows desktop scaling is at 100%.

**Comment by Crypto90** [comment]
I improved the logging a lot with version 1.9.1 and it showed me, that lower resolutions of the game renders the text of the sockets ingame more blurry/washed out/anti aliased which results in this behavior. Larger resolutions work perfectly fine.

The current color matching is done by a color search pixel by pixel in the needed area and returns true if the color with a slight tolerance got found. This returns on the "first pixel found with the searched color".

A more better way to resolve this issue is to check the whole scan area colors and create a color map which gives us a percentage of color in the image. So we can check which percentage of color is the highest for matching.

I am currently working on this.

**Comment by Crypto90** [comment]
Version 1.9.2 got released. It now includes euclidean distance color matching for rock solid results.
No more color missmatches.

**Comment by steavewithana** [comment]
1.9.0 is working much better. Being able to change the sleep setting client
side has made a big improvement when ping is high. Amazing tool.

**Comment by Crypto90** [comment]
Thanks, I am glad you like it.
